### ISSUE TITLE
软件闪退

### ISSUE THREAD

**Issue by yanygm** [tuuzed/WMirror#2]
java.io.FileNotFoundException: /data/local/tmp/classes.jar: open failed: EACCES (Permission denied)
 at libcore.io.IoBridge.open(IoBridge.java:496)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
 at m.a.r.l.a.a.b(Unknown Source:26)
 at m.a.r.i.i(:1)
 at l.m.j.a.a.f(:2)
 at h.a.k0.run(:2)
 at h.a.u1.a.E(Unknown Source:0)
 at h.a.u1.a$a.run(:38)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
 at libcore.io.Linux.open(Native Method)
 at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
 at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
 at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
 at android.app.ActivityThread$AndroidOs.open(Unknown Source:15)
 at libcore.io.IoBridge.open(IoBridge.java:482)
 ... 8 more

**Comment by yanygm** [comment]
小米K20
Android 10
MIUI 12
Magisk root

**Comment by tuuzed** [comment]
这个应该是Root插件有问题，可以先试一下最新版本的MirrorApp
